package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"my_gql_server/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateIcon is the resolver for the createIcon field.
func (r *mutationResolver) CreateIcon(ctx context.Context, input model.NewIcon) (*model.Icon, error) {
	panic(fmt.Errorf("not implemented: CreateIcon - createIcon"))
}

// UpdateIcon is the resolver for the updateIcon field.
func (r *mutationResolver) UpdateIcon(ctx context.Context, input model.UpdateIcon) (*model.Icon, error) {
	panic(fmt.Errorf("not implemented: UpdateIcon - updateIcon"))
}

// DeleteIcon is the resolver for the deleteIcon field.
func (r *mutationResolver) DeleteIcon(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteIcon - deleteIcon"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// UserRegistrationStatus is the resolver for the UserRegistrationStatus field.
func (r *queryResolver) UserRegistrationStatus(ctx context.Context, accountID string) (*model.UserRegistrationStatus, error) {
	return r.Srv.GetUserRegistrationStatus(accountID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
