// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
	Age   *int    `json:"age,omitempty"`
	Work  *string `json:"work,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   int    `json:"age"`
	Work  string `json:"work"`
}
